window.sentlog=window.sentlog||{referrer:!1};window.site_name=window.site_name||"58";var json_trackPagetype="NA",json_trackURL="NA",json_trackParams="NA",json_trackPageview="NA";"undefined"!=typeof ____json4fe&&("_trackPagetype"in ____json4fe&&(json_trackPagetype=____json4fe._trackPagetype),"_trackURL"in ____json4fe&&(json_trackURL=____json4fe._trackURL),"_trackParams"in ____json4fe&&(json_trackParams=____json4fe._trackParams),"_trackPageview"in ____json4fe&&(json_trackPageview=____json4fe._trackPageview));
window.tgreg=window.tgreg||-1;window._trackURL=window._trackURL||json_trackURL||"NA";window._trackParams=window._trackParams||json_trackParams||"NA";var referrer=encodeURIComponent(document.referrer),pagetypeTmp,post_countTmp,cateTmp="",areaTmp="",GA_pageviewTmp="";
if("NA"!=_trackURL){var trackJsonStr=eval("("+_trackURL+")");trackJsonStr.pagetype&&(pagetypeTmp=trackJsonStr.pagetype);trackJsonStr.post_count&&(post_countTmp=trackJsonStr.post_count);trackJsonStr.cate&&(cateTmp=trackJsonStr.cate);trackJsonStr.area&&(areaTmp=trackJsonStr.area);trackJsonStr.GA_pageview&&(GA_pageviewTmp=trackJsonStr.GA_pageview)}window.page_type=window.page_type||pagetypeTmp||json_trackPagetype||"NA";window.post_count=window.post_count||post_countTmp||-1;
if("NA"!=json_trackPageview)if("NA"!=_trackURL){var tmpArr=_trackURL.split("{");_trackURL=tmpArr[0]+"{'GA_pageview':'"+json_trackPageview+"',"+tmpArr[1]}else _trackURL="{'GA_pageview':'"+json_trackPageview+"'}";
if("NA"!=_trackURL&&-1!=_trackURL.indexOf("GA_pageview")&&"post"!=page_type)try{window._gaq=window._gaq||[],window._gaq.push(["pageTracker._setAccount","UA-877409-4"]),window._gaq.push(["pageTracker._setDomainName",".58.com"]),window._gaq.push(["pageTracker._setAllowLinker",!0]),window._gaq.push(["pageTracker._addOrganic","sogou","query"]),window._gaq.push(["pageTracker._addOrganic","baidu","word"]),window._gaq.push(["pageTracker._addOrganic","soso","w"]),window._gaq.push(["pageTracker._addOrganic",
"youdao","q"]),window._gaq.push(["pageTracker._addOrganic","360","q"]),window._gaq.push(["pageTracker._trackPageLoadTime"]),-1!=_trackURL.indexOf("'GA_pageview':''")?window._gaq.push(["pageTracker._trackPageview"]):(trackJsonStr=eval("("+_trackURL+")"),trackJsonStr.GA_pageview&&(ga_pageviewStr=trackJsonStr.GA_pageview,window._gaq.push(["pageTracker._trackPageview",ga_pageviewStr]))),setTimeout(function(){var b="https:"==document.location.protocol?" https://ssl":" http://www",a=document.createElement("script");
a.type="text/javascript";a.src=b+".google-analytics.com/ga.js";document.getElementsByTagName("head")[0].appendChild(a)},2E3)}catch(e_ga){}var GTID=Math.random(),GTID=(new Date).valueOf()+""+GTID,ClickID=1,curURL=window.location.href;"NA"==_trackURL?_trackURL="{'GTID':'"+GTID+"'}":(tmpArr=_trackURL.split("{"),_trackURL=tmpArr[0]+"{'GTID':'"+GTID+"',"+tmpArr[1]);
if(window.$){(function(){-1!=(_trackURL||"NA").indexOf("'pagetype':'home'")&&$("[href]").bind("click",function(b){var a=$(this).attr("href"),c=$(this).offset().top,e=$(this).offset().left;clickLog("from=heatmap:"+a+"&tagX="+e+"&tagY="+c+"&mouseX="+b.pageX+"&mouseY="+b.pageY)})})();(function(){$("[tongji_id]").bind("click",function(b){var a=b.srcElement?b.srcElement:b.target;"A"==a.tagName.toUpperCase()&&(b=$(a).attr("href")||"#",a=$(a).text(),-1==b.indexOf("javascript:")&&"#"!=b.substring(0,1)&&clickLog("from="+
$(this).attr("tongji_id")+"&text="+encodeURIComponent(a)+"&to="+encodeURIComponent(b)))})})();(function(){$("[tongji_tag]").bind("click",function(){var b=$(this).attr("tongji_tag");clickLog("from="+b)})})();try{$("#zp_recommend").delegate&&$("#zp_recommend").delegate("a","click",function(){var b=ClickID;if("NO"==filterList(curURL)&&-1!=curURL.indexOf(".58.com")){var a=$(this).attr("href")||"#";-1!=a.indexOf("javascript:")||"#"==a.substring(0,1)||"NO"!=filterList(a)||"/"!=a.substring(0,1)&&-1==a.indexOf(".58.com")||
(a.match(/[\?&]PGTID=[^&]*&ClickID=\d*/)?$(this).attr("href",a.replace(/PGTID=[^&]*&ClickID=\d*/,"PGTID="+GTID+"&ClickID="+b)):$(this).attr("href",$.trim(a)+(-1==a.indexOf("?")?"?":"&")+"PGTID="+GTID+"&ClickID="+b))}})}catch(e$$14){}$("a").bind("click",function(){var b=ClickID;if("NO"==filterList(curURL)&&-1!=curURL.indexOf(".58.com")){var a=$(this).attr("href")||"#";-1!=a.indexOf("javascript:")||"#"==a.substring(0,1)||"NO"!=filterList(a)||"/"!=a.substring(0,1)&&-1==a.indexOf(".58.com")||(a.match(/[\?&]PGTID=[^&]*&ClickID=\d*/)?
$(this).attr("href",a.replace(/PGTID=[^&]*&ClickID=\d*/,"PGTID="+GTID+"&ClickID="+b)):$(this).attr("href",$.trim(a)+(-1==a.indexOf("?")?"?":"&")+"PGTID="+GTID+"&ClickID="+b))}})}
if(-1!=curURL.indexOf("post.58.com")||!sentlog.referrer){_trackParams=format_trackParams(_trackParams);_trackParams=encodeURIComponent(_trackParams);var logmsg="tag=pvstatall&referrer="+referrer+"&type="+page_type+"&post_count="+post_count+"&_trackParams="+_trackParams;if("detail"==page_type||"jianli_detail"==page_type)try{logmsg=logmsg+"&userid="+____json4fe.userid,"phone"in ____json4fe&&(logmsg=logmsg+"&huzhuan="+____json4fe.phone),0<tgreg&&(logmsg=logmsg+"&tgreg="+tgreg)}catch(e$$15){}try{if("version"in
____json4fe&&(logmsg=logmsg+"&version="+____json4fe.version),"smsc"in ____json4fe&&(logmsg=logmsg+"&smsc="+____json4fe.smsc),"start"in ____json4fe&&(logmsg+="&loadtime="+((new Date).getTime()-____json4fe.start)),"supplycount"in ____json4fe)for(var attr in ____json4fe.supplycount)logmsg=logmsg+"&supplycount."+attr+"="+____json4fe.supplycount[attr]}catch(e$$16){}try{logmsg=logmsg+"&window_size="+document.documentElement.clientWidth+"x"+document.documentElement.clientHeight}catch(e$$17){}try{var m_ga_utma=
getcookie("__utma");m_ga_utma&&""!=m_ga_utma&&(logmsg=logmsg+"&_ga_utma="+m_ga_utma);var init_refer=referrer,cookie_init_refer=getcookie("init_refer"),cookie_new_session=getcookie("new_session");cookie_new_session&&""!=cookie_new_session?(setcookie_session("new_session","0"),setcookie_session("init_refer",cookie_init_refer),"NA"!=_trackURL?(tmpArr=_trackURL.split("{"),_trackURL=tmpArr[0]+"{'new_session':'0','init_refer':'"+cookie_init_refer+"',"+tmpArr[1]):_trackURL="{'new_session':'0','init_refer':'"+
cookie_init_refer+"'}"):(setcookie_session("new_session","1"),setcookie_session("init_refer",init_refer),"NA"!=_trackURL?(tmpArr=_trackURL.split("{"),_trackURL=tmpArr[0]+"{'new_session':'1','init_refer':'"+init_refer+"',"+tmpArr[1]):_trackURL="{'new_session':'1','init_refer':'"+init_refer+"'}");var cookie_new_uv=getcookie("new_uv");cookie_new_uv&&""!=cookie_new_uv?cookie_new_session&&""!=cookie_new_session||cookie_new_uv++:cookie_new_uv=1;setcookie("new_uv",cookie_new_uv,365);"NA"!=_trackURL?(tmpArr=
_trackURL.split("{"),_trackURL=tmpArr[0]+"{'new_uv':'"+cookie_new_uv+"',"+tmpArr[1]):_trackURL="{'new_uv':'"+cookie_new_uv+"'}"}catch(e$$18){}"NA"!=_trackURL&&(logmsg=logmsg+"&trackURL="+_trackURL);ajaxlog_new(logmsg);"NA"!=_trackURL&&"NA"!=pagetypeTmp&&"list"==pagetypeTmp&&ajaxlog_pclistshow(_trackURL);try{var cnzz_protocol="https:"==document.location.protocol?" https://":" http://",sNode=document.createElement("script");sNode.type="text/javascript";sNode.src=cnzz_protocol+"w.cnzz.com/c.php?id=30017898";
document.getElementsByTagName("head")[0].appendChild(sNode)}catch(e_cnzz){}sentlog.referrer=!0}function setcookie(b,a,c){var e=new Date;e.setTime(e.getTime()+864E5*c);document.cookie=b+"="+escape(a)+"; expires="+e.toGMTString()+"; domain=.58.com; path=/"}function setcookie_session(b,a){var c=new Date;c.setTime(c.getTime()+18E5);document.cookie=b+"="+escape(a)+"; expires="+c.toGMTString()+"; domain=.58.com; path=/"}
function getcookie(b){var a;return(a=document.cookie.match(RegExp("(^| )"+b+"=([^;]*)(;|$)")))?unescape(a[2]):""}function ajaxsend(b){(new Image).src=b}function ajaxlog(b){ajaxsend(document.location.protocol+"//track.58.com/empty.js.gif?site_name="+site_name+"&"+b+"&rand="+Math.random());ajaxsend(document.location.protocol+"//tracklog1.58.com/pc/empty.js.gif?site_name="+site_name+"&"+b+"&rand="+Math.random())}
function ajaxlog_new(b){var a=Math.random();ajaxsend(document.location.protocol+"//tracklog1.58.com/pc/empty.js.gif?fromid=referrer4&site_name="+site_name+"&"+b+"&rand_id="+a);var c=_trackURL||"NA";if(-1!=c.indexOf("'pagetype':'detail'")||-1!=c.indexOf("'pagetype':'jianli_detail'"))-1==c.indexOf("'cate':'9224")&&-1==c.indexOf("'cate':'9225")&&-1==c.indexOf("'cate':'13941")&&-1==c.indexOf("'cate':'13952")||ajaxsend(document.location.protocol+"//dialog.58.com/transfer?DIATag=PCTrack&"+b+"&rand_id="+
a);"list"==pagetypeTmp&&(b=GA_pageviewTmp.indexOf("?key="),a="",-1!=b&&(a=GA_pageviewTmp.substring(b+5)),ajaxsend(document.location.protocol+"//gdt.cm.58.com/gdtcm?city="+areaTmp+"&cate="+cateTmp+"&key="+a+"&plat=PC"))}function ajaxlog2(b){ajaxlog(b)}function ajaxlogr(b){ajaxsend(document.location.protocol+"//tracklog1.58.com/pc/click/listclicklog?site_name="+site_name+"&"+b+"&trackURL="+_trackURL+"&ClickID="+ClickID+"&referrer="+referrer+"&rand="+Math.random());setTimeout("ClickIDPlus()",300)}
function format_trackParams(b){if("NA"==b)return b;try{for(var a=[],c=0,e=b.length;c<e;c++)a.push(b[c].I+":"+b[c].V.replace(/\|/g,"*"));return a.join("@@")}catch(d){return"error"}}
function clickLog(b){var a=getcookie("bangbangid");a&&""!=a||(a="");var c=ClickID;ajaxsend(document.location.protocol+"//tracklog1.58.com/pc/click/empty.js.gif?site_name="+site_name+"&tag=pvsiters&"+b+"&trackURL="+_trackURL+"&ClickID="+c+"&bangbangid="+a+"&referrer="+referrer+"&rand="+Math.random());ajaxsend(document.location.protocol+"//tracklog1.58.com/PCv1/click/empty.js.gif?site_name="+site_name+"&tag=pcclick&"+b+"&trackURL="+_trackURL+"&ClickID="+c+"&bangbangid="+a+"&referrer="+referrer+"&rand="+
Math.random());-1!=b.indexOf("&ROI=")&&ajaxsend(document.location.protocol+"//dialog.58.com/transfer?DIATag=PCClick&"+b+"&trackURL="+_trackURL+"&ClickID="+c+"&bangbangid="+a+"&referrer="+referrer+"&rand="+Math.random());setTimeout("ClickIDPlus()",300)}function ClickIDPlus(){ClickID+=1}
function showLog(b){var a=getcookie("bangbangid");a&&""!=a||(a="");ajaxsend(document.location.protocol+"//dialog.58.com/transfer?DIATag=PCTuijianShow&"+b+"&trackURL="+_trackURL+"&bangbangid="+a+"&referrer="+referrer+"&rand="+Math.random())}function filterList(b){var a=".58.com.cn portal.58.com faw-vw-dasweltauto.58.com 5858.com lieche.58.com dict.58.com/xiaoqu about.58.com".split(" "),c;for(c in a)if(-1!=b.indexOf(a[c]))return"YES";return"NO"}
function ajaxlog_pclistshow(b){try{if(window.$){var a=getcookie("bangbangid");a&&""!=a||(a="");var c=Math.random();data_arr=[];"NA"!=cateTmp&&cateTmp.split(",");for(var e=$("[logr]"),d=0,f=e.length;d<f;d++)if($(e[d]).attr("logr")){var k=[],g="",h=$(e[d]).attr("logr").split("_");k.push(h[0],h[1],h[2],h[3]);var m=$(e[d]).attr("_pos"),n=d+1,p=$(e[d]).attr("sortid"),l=h[h.length-1];l&&-1!=l.indexOf("ses^")&&(l=l.replace("ses^","ses:"),g+=l);p&&(g+="@sortid:"+p);n&&(g+="@pos:"+n);m&&(g+="@npos:"+m);""!=
g&&k.push(g);data_arr.push(k.join("_"))}ajaxsend(document.location.protocol+"//tracklog1.58.com/PCv1/listshow/empty.js.gif?tag=pclistshow&fromid=referrer4&bangbangid="+a+"&referrer="+referrer+"&site_name="+site_name+"&info_data="+data_arr.join(",")+"&trackURL="+b+"&rand_id="+c)}}catch(q){ajaxsend(document.location.protocol+"//tracklog1.58.com/PCv1/listshow/empty.js.gif?tag=pclistshow&fromid=referrer4&Error="+q)}}
if(window.$)try{(function(){$("[logr]").bind("click",function(){var b=getcookie("bangbangid");b&&""!=b||(b="");var a="",c=ClickID,e=Math.random(),a=[],d="",f=$(this).attr("logr").split("_");a.push(f[0],f[1],f[2],f[3]);var k=$(this).attr("_pos"),g=$("[logr]").index($(this))+1,h=$(this).attr("sortid");(f=f[f.length-1])&&-1!=f.indexOf("ses^")&&(f=f.replace("ses^","ses:"),d+=f);h&&(d+="@sortid:"+h);g&&(d+="@pos:"+g);k&&(d+="@npos:"+k);""!=d&&a.push(d);a=a.join("_");ajaxsend(document.location.protocol+
"//tracklog1.58.com/PCv1/listclick/empty.js.gif?tag=pclistclick&fromid=referrer4&bangbangid="+b+"&referrer="+referrer+"&site_name="+site_name+"&info_data="+a+"&trackURL="+_trackURL+"&ClickID="+c+"&rand_id="+e);setTimeout("ClickIDPlus()",300)})})()}catch(e$$21){ajaxsend(document.location.protocol+"//tracklog1.58.com/PCv1/listclick/empty.js.gif?tag=pclistclick&fromid=referrer4&Error="+e$$21)};
