//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.OrderInfo = new HashSet<OrderInfo>();
        }
    
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPwd { get; set; }
        public System.DateTime SubTime { get; set; }
    
        public virtual ICollection<OrderInfo> OrderInfo { get; set; }
    }
}
