//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersinfo
    {
        public int uid { get; set; }
        public string uaccount { get; set; }
        public string upassword { get; set; }
        public string uphone { get; set; }
        public string uemail { get; set; }
        public string udatetime { get; set; }
    }
}
